/**
 * Build `lib/client.js`: the browser-half bundle the client module system
 * serves for `exports["./client"]`.
 *
 * The browser half has no React components, no CSS and no platform-module
 * requests. The module loader requires one script that registers a factory:
 *
 *   window.__ModuleLoader__.load({ id, factory: (require) => exports })
 *
 * This script transpiles each `src/client/*.ts` file, strips the relative
 * imports (the project's own modules are concatenated in dependency order),
 * and wraps the result in that contract.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const srcDir = join(root, 'src', 'client');
const outFile = join(root, 'lib', 'client.js');
const packageName = 'dsh-plugin-template';

/**
 * Concatenation order: constants/types first, entry last.
 * Adjust when adding new modules.
 */
const MODULES = ['index.ts'];

/** Load the TypeScript compiler, preferring a local install. */
function loadTypeScript() {
  const require = createRequire(import.meta.url);
  const candidates = ['typescript', process.env.DSH_TYPESCRIPT];
  for (const candidate of candidates) {
    if (candidate === undefined) continue;
    try {
      return require(candidate);
    } catch {
      // Try the next candidate.
    }
  }
  throw new Error(
    'typescript not found: install it in this package, or point DSH_TYPESCRIPT at a tsc module directory',
  );
}

/** Drop relative imports: their modules are concatenated into this bundle. */
function stripRelativeImports(code) {
  return code
    .split('\n')
    .filter(line => !/^\s*import\b[^;]*from\s+['"]\.\/[^'"]+['"];?\s*$/.test(line))
    .filter(line => !/^\s*import\s+['"]\.\/[^'"]+['"];?\s*$/.test(line))
    .join('\n');
}

/**
 * Drop module-level `export` keywords: every module shares one factory closure,
 * so only the entry's `apply`/`inject` are exported.
 */
function stripExportKeywords(code) {
  return code
    .split('\n')
    .map(line => line.replace(/^(\s*)export\s+(?=(?:const|let|var|function|class|interface|enum|async)\b)/, '$1'))
    .map(line => line.replace(/^(\s*)export\s+default\s+/, '$1'))
    .join('\n');
}

/** Transpile one TypeScript module to erasable JavaScript. */
function transpile(ts, fileName, source) {
  const result = ts.transpileModule(source, {
    fileName,
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      removeComments: false,
    },
  });
  return stripExportKeywords(stripRelativeImports(result.outputText)).trim();
}

/** Build the bundle text from the transpiled modules. */
function composeBundle(parts) {
  return [
    `// ${packageName} — browser half (client module-loader bundle).`,
    '// Generated by scripts/build-client.mjs from src/client/*.ts; edit the sources, not this file.',
    'window.__ModuleLoader__.load({',
    `  id: ${JSON.stringify(packageName)},`,
    '  factory: (require) => {',
    '    const module = { exports: {} };',
    '    const exports = module.exports;',
    ...parts.map(part => part.replace(/^(?=.)/gm, '    ')),
    '    exports.inject = inject;',
    '    exports.apply = apply;',
    '    return module.exports;',
    '  },',
    '});',
    '',
  ].join('\n');
}

const ts = loadTypeScript();
const parts = [];
for (const name of MODULES) {
  const source = await readFile(join(srcDir, name), 'utf8');
  parts.push(transpile(ts, name, source));
}

const bundle = composeBundle(parts);
if (!bundle.includes('exports.apply = apply;')) {
  throw new Error('bundle is missing the apply export');
}
if (/\brequire\(['"]/.test(bundle.replace(/factory: \(require\)/, ''))) {
  throw new Error('bundle must not contain a module request');
}

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, bundle, 'utf8');
console.log(`wrote ${outFile} (${bundle.length} chars)`);
